"""Multi-site XLSX export service.

Generates an XLSX workbook in the sites-template format:
- INSTRUCTIONS tab (static)
- One tab per project (tab name = domain from site_url)
- Columns: page_type, Title, title, meta_description, h1, Top description, Bottom Description, Blog Content
- Collection rows from CrawledPage + PageContent
- Blog rows from BlogPost
"""

import io
import re
from urllib.parse import urlparse

from openpyxl import Workbook
from openpyxl.styles import Alignment, Font
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.orm import selectinload

from app.models.blog import BlogCampaign, BlogPost
from app.models.crawled_page import CrawledPage
from app.models.page_content import PageContent
from app.models.project import Project


# Column headers matching sites-template.xlsx
COLUMNS = [
    "page_type",
    "Title",
    "title",
    "meta_description",
    "h1",
    "Top description",
    "Bottom Description",
    "Blog Content",
]


def _domain_from_url(site_url: str) -> str:
    """Extract domain from a site URL (e.g., 'https://example.com' -> 'example.com')."""
    parsed = urlparse(site_url)
    domain = parsed.netloc or parsed.path
    # Strip www. prefix
    if domain.startswith("www."):
        domain = domain[4:]
    return domain


def _sanitize_sheet_name(name: str) -> str:
    """Sanitize a string for use as an Excel sheet name.

    Excel limits: 31 chars, no []:*?/\\
    """
    # Remove invalid characters
    cleaned = re.sub(r"[\[\]:*?/\\]", "", name)
    # Truncate to 31 chars
    if len(cleaned) > 31:
        # Try dropping TLD first
        without_tld = re.sub(r"\.[a-z]+$", "", cleaned)
        if len(without_tld) <= 31:
            cleaned = without_tld
        else:
            cleaned = cleaned[:31]
    return cleaned or "Sheet"


def _write_instructions_sheet(ws: any) -> None:
    """Write the INSTRUCTIONS tab with static documentation."""
    ws.column_dimensions["A"].width = 100

    instructions = [
        "Lorem Ipsum SEO Generator — XLSX Export",
        "",
        "HOW THIS FILE IS STRUCTURED",
        "",
        "1. Each tab = one website. Tab name = the domain.",
        "2. Each row = one page (collection or blog post).",
        "3. Homepage and product pages are auto-generated by the static site generator.",
        "",
        "COLUMNS",
        "",
        "  page_type         — 'collection' or 'blog'",
        "  Title              — Page title (primary keyword in Title Case)",
        "  title              — SEO title tag (shown in search results and browser tab)",
        "  meta_description   — ~155 chars (shown in search results)",
        "  h1                 — Page heading (defaults to title if blank)",
        "  Top description    — Short text shown below the H1 (collections only)",
        "  Bottom Description — HTML content below the product grid (collections only)",
        "  Blog Content       — Full HTML article body (blog posts only)",
        "",
        "CONTENT STRATEGY",
        "",
        "  Headings (<h2>, <h3>)   -> MUST contain the primary keyword",
        "  Body paragraphs (<p>)   -> Lorem ipsum placeholder text",
        "  Meta descriptions       -> Keyword-loaded, reads naturally",
        "",
        "GENERATED BY",
        "",
        "  This file was exported from Grove SEO Test instance.",
    ]

    for i, line in enumerate(instructions, start=1):
        cell = ws.cell(row=i, column=1, value=line)
        if i == 1:
            cell.font = Font(bold=True, size=14)
        elif line and not line.startswith(" "):
            cell.font = Font(bold=True)
        cell.alignment = Alignment(wrap_text=True)


async def generate_sites_xlsx(
    db: AsyncSession,
    project_ids: list[str] | None = None,
) -> io.BytesIO:
    """Generate a multi-site XLSX workbook.

    Args:
        db: Async database session.
        project_ids: Optional list of project IDs to include.
            If None, includes all projects.

    Returns:
        BytesIO buffer containing the XLSX file.
    """
    # Fetch projects
    stmt = select(Project).order_by(Project.name)
    if project_ids:
        stmt = stmt.where(Project.id.in_(project_ids))
    result = await db.execute(stmt)
    projects = list(result.scalars().all())

    if not projects:
        raise ValueError("No projects available for export")

    wb = Workbook()

    # Remove default sheet
    wb.remove(wb.active)

    # INSTRUCTIONS tab
    instructions_ws = wb.create_sheet("INSTRUCTIONS")
    _write_instructions_sheet(instructions_ws)

    # One tab per project
    for project in projects:
        domain = _domain_from_url(project.site_url)
        sheet_name = _sanitize_sheet_name(domain)

        # Ensure unique sheet names
        existing_names = [ws.title for ws in wb.worksheets]
        if sheet_name in existing_names:
            sheet_name = _sanitize_sheet_name(f"{sheet_name}-{project.id[:4]}")

        ws = wb.create_sheet(sheet_name)

        # Header row
        for col_idx, header in enumerate(COLUMNS, start=1):
            cell = ws.cell(row=1, column=col_idx, value=header)
            cell.font = Font(bold=True)

        # Set column widths
        ws.column_dimensions["A"].width = 12  # page_type
        ws.column_dimensions["B"].width = 40  # Title (page title)
        ws.column_dimensions["C"].width = 50  # title (SEO title)
        ws.column_dimensions["D"].width = 60  # meta_description
        ws.column_dimensions["E"].width = 50  # h1
        ws.column_dimensions["F"].width = 60  # Top description
        ws.column_dimensions["G"].width = 80  # Bottom Description
        ws.column_dimensions["H"].width = 80  # Blog Content

        row_idx = 2

        # --- Collection rows (CrawledPage + PageContent) ---
        pages_stmt = (
            select(CrawledPage)
            .options(
                selectinload(CrawledPage.page_content),
                selectinload(CrawledPage.keywords),
            )
            .where(CrawledPage.project_id == project.id)
            .order_by(CrawledPage.normalized_url)
        )
        pages_result = await db.execute(pages_stmt)
        pages = list(pages_result.scalars().all())

        # Filter to pages with complete content, sort by title
        collection_rows = []
        for page in pages:
            pc = page.page_content
            if pc and pc.status == "complete":
                pk = page.keywords
                page_title = (pk.primary_keyword.title() if pk and pk.primary_keyword else "")
                collection_rows.append(
                    {
                        "page_type": "collection",
                        "page_title": page_title,
                        "title": pc.page_title or "",
                        "meta_description": pc.meta_description or "",
                        "h1": pc.page_title or "",
                        "top_description": pc.top_description or "",
                        "bottom_description": pc.bottom_description or "",
                        "blog_content": "",
                    }
                )
        collection_rows.sort(key=lambda r: r["title"])

        for row_data in collection_rows:
            ws.cell(row=row_idx, column=1, value=row_data["page_type"])
            ws.cell(row=row_idx, column=2, value=row_data["page_title"])
            ws.cell(row=row_idx, column=3, value=row_data["title"])
            ws.cell(row=row_idx, column=4, value=row_data["meta_description"])
            ws.cell(row=row_idx, column=5, value=row_data["h1"])
            ws.cell(row=row_idx, column=6, value=row_data["top_description"])
            ws.cell(row=row_idx, column=7, value=row_data["bottom_description"])
            ws.cell(row=row_idx, column=8, value=row_data["blog_content"])
            row_idx += 1

        # --- Blog rows (BlogPost via BlogCampaign) ---
        campaigns_stmt = (
            select(BlogCampaign)
            .options(selectinload(BlogCampaign.posts))
            .where(BlogCampaign.project_id == project.id)
        )
        campaigns_result = await db.execute(campaigns_stmt)
        campaigns = list(campaigns_result.scalars().all())

        blog_rows = []
        for campaign in campaigns:
            for post in (campaign.posts or []):
                if post.content:  # Has generated content
                    page_title = (post.primary_keyword.title() if post.primary_keyword else "")
                    blog_rows.append(
                        {
                            "page_type": "blog",
                            "page_title": page_title,
                            "title": post.title or "",
                            "meta_description": post.meta_description or "",
                            "h1": post.title or "",
                            "top_description": "",
                            "bottom_description": "",
                            "blog_content": post.content or "",
                        }
                    )
        blog_rows.sort(key=lambda r: r["title"])

        for row_data in blog_rows:
            ws.cell(row=row_idx, column=1, value=row_data["page_type"])
            ws.cell(row=row_idx, column=2, value=row_data["page_title"])
            ws.cell(row=row_idx, column=3, value=row_data["title"])
            ws.cell(row=row_idx, column=4, value=row_data["meta_description"])
            ws.cell(row=row_idx, column=5, value=row_data["h1"])
            ws.cell(row=row_idx, column=6, value=row_data["top_description"])
            ws.cell(row=row_idx, column=7, value=row_data["bottom_description"])
            ws.cell(row=row_idx, column=8, value=row_data["blog_content"])
            row_idx += 1

    # Save to buffer
    buffer = io.BytesIO()
    wb.save(buffer)
    buffer.seek(0)
    return buffer
