"""widen internal_links status column to 100 chars

Revision ID: da1ea5f253b0
Revises: 0025
Create Date: 2026-02-10 16:55:49.904527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da1ea5f253b0'
down_revision: Union[str, None] = '0025'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_competitors_project_url_unique'), table_name='competitors')
    op.drop_constraint(op.f('fk_competitors_project_id'), 'competitors', type_='foreignkey')
    op.drop_index(op.f('ix_content_scores_scored_at'), table_name='content_scores')
    op.drop_index(op.f('ix_crawl_history_started_at'), table_name='crawl_history')
    op.drop_constraint(op.f('fk_crawl_history_project_id'), 'crawl_history', type_='foreignkey')
    op.drop_constraint(op.f('fk_crawl_history_schedule_id'), 'crawl_history', type_='foreignkey')
    op.drop_index(op.f('ix_crawl_schedules_is_active'), table_name='crawl_schedules')
    op.drop_index(op.f('ix_crawl_schedules_next_run_at'), table_name='crawl_schedules')
    op.drop_constraint(op.f('fk_crawl_schedules_project_id'), 'crawl_schedules', type_='foreignkey')
    op.drop_index(op.f('ix_crawled_pages_project_url_unique'), table_name='crawled_pages')
    op.drop_constraint(op.f('fk_crawled_pages_project_id'), 'crawled_pages', type_='foreignkey')
    op.alter_column('internal_links', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=100),
               existing_nullable=False,
               existing_server_default=sa.text("'planned'::character varying"))
    op.drop_index(op.f('ix_nlp_analysis_cache_lookup'), table_name='nlp_analysis_cache')
    op.drop_constraint(op.f('fk_nlp_analysis_cache_project_id'), 'nlp_analysis_cache', type_='foreignkey')
    op.drop_constraint(op.f('uq_notification_templates_name'), 'notification_templates', type_='unique')
    op.drop_constraint(op.f('uq_page_contents_crawled_page_id'), 'page_contents', type_='unique')
    op.drop_index(op.f('ix_page_contents_crawled_page_id'), table_name='page_contents')
    op.create_index(op.f('ix_page_contents_crawled_page_id'), 'page_contents', ['crawled_page_id'], unique=True)
    op.drop_constraint(op.f('fk_page_paa_crawled_page_id'), 'page_paa', type_='foreignkey')
    op.drop_constraint(op.f('uq_webhook_configs_name'), 'webhook_configs', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_webhook_configs_name'), 'webhook_configs', ['name'], postgresql_nulls_not_distinct=False)
    op.create_foreign_key(op.f('fk_page_paa_crawled_page_id'), 'page_paa', 'crawled_pages', ['crawled_page_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_page_contents_crawled_page_id'), table_name='page_contents')
    op.create_index(op.f('ix_page_contents_crawled_page_id'), 'page_contents', ['crawled_page_id'], unique=False)
    op.create_unique_constraint(op.f('uq_page_contents_crawled_page_id'), 'page_contents', ['crawled_page_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_notification_templates_name'), 'notification_templates', ['name'], postgresql_nulls_not_distinct=False)
    op.create_foreign_key(op.f('fk_nlp_analysis_cache_project_id'), 'nlp_analysis_cache', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_nlp_analysis_cache_lookup'), 'nlp_analysis_cache', ['project_id', 'competitor_url', 'analysis_type'], unique=False)
    op.alter_column('internal_links', 'status',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'planned'::character varying"))
    op.create_foreign_key(op.f('fk_crawled_pages_project_id'), 'crawled_pages', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_crawled_pages_project_url_unique'), 'crawled_pages', ['project_id', 'normalized_url'], unique=True)
    op.create_foreign_key(op.f('fk_crawl_schedules_project_id'), 'crawl_schedules', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_crawl_schedules_next_run_at'), 'crawl_schedules', ['next_run_at'], unique=False)
    op.create_index(op.f('ix_crawl_schedules_is_active'), 'crawl_schedules', ['is_active'], unique=False)
    op.create_foreign_key(op.f('fk_crawl_history_schedule_id'), 'crawl_history', 'crawl_schedules', ['schedule_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_crawl_history_project_id'), 'crawl_history', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_crawl_history_started_at'), 'crawl_history', ['started_at'], unique=False)
    op.create_index(op.f('ix_content_scores_scored_at'), 'content_scores', ['scored_at'], unique=False)
    op.create_foreign_key(op.f('fk_competitors_project_id'), 'competitors', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_competitors_project_url_unique'), 'competitors', ['project_id', 'url'], unique=True)
    # ### end Alembic commands ###
