"""Schemas layer - Pydantic models for API validation.

Schemas define the shape of data for API requests and responses.
They handle validation, serialization, and documentation.
"""

from app.schemas.blog import (
    BlogBulkApproveResponse,
    BlogCampaignCreate,
    BlogCampaignListItem,
    BlogCampaignResponse,
    BlogContentGenerationStatus,
    BlogContentTriggerResponse,
    BlogContentUpdateRequest,
    BlogExportItem,
    BlogLinkMapItem,
    BlogLinkMapResponse,
    BlogLinkPlanTriggerResponse,
    BlogLinkStatusResponse,
    BlogPostGenerationStatusItem,
    BlogPostResponse,
    BlogPostUpdate,
)
from app.schemas.brand_config import (
    VALID_SECTION_NAMES,
    BrandConfigResponse,
    RegenerateRequest,
    SectionUpdate,
)
from app.schemas.brand_config_generation import (
    GenerationStatusResponse,
)
from app.schemas.categorize import (
    BatchPageRequest,
    CategorizeAllRequest,
    CategorizeAllResponse,
    CategorizeBatchRequest,
    CategorizedPageResponse,
    CategorizePageIdsRequest,
    CategorizePageIdsResponse,
    CategorizeRequest,
    CategorizeResponse,
    CategorizeStatsResponse,
    ContentAnalysisResponse,
    ContentSignalResponse,
    UpdateCategoryRequest,
    UpdateCategoryResponse,
)
from app.schemas.cluster import (
    ClusterCreate,
    ClusterListResponse,
    ClusterPageResponse,
    ClusterPageUpdate,
    ClusterResponse,
)
from app.schemas.content_brief import (
    CompetitorSchema,
    ContentBriefBatchItemResponse,
    ContentBriefBatchRequest,
    ContentBriefBatchResponse,
    ContentBriefCreateResponse,
    ContentBriefRequest,
    ContentBriefResponse,
    ContentBriefStatsResponse,
    EntitySchema,
    HeadingTargetSchema,
    KeywordTargetSchema,
    LSITermSchema,
    RelatedQuestionSchema,
    RelatedSearchSchema,
)
from app.schemas.content_generation import (
    BriefSummary,
    ContentGenerationStatus,
    ContentGenerationTriggerResponse,
    PageContentResponse,
    PageGenerationStatusItem,
    PromptLogResponse,
)
from app.schemas.content_score import (
    ContentScoreBatchItemResponse,
    ContentScoreBatchRequest,
    ContentScoreBatchResponse,
    ContentScoreCreateResponse,
    ContentScoreRequest,
    ContentScoreResponse,
    ContentScoreStatsResponse,
    HeadingAnalysisSchema,
    HeadingLevelAnalysisSchema,
    KeywordAnalysisSchema,
    KeywordSectionAnalysisSchema,
    LSICoverageItemSchema,
    LSICoverageSchema,
    RecommendationSchema,
)
from app.schemas.crawl import (
    VALID_CRAWL_STATUSES,
    VALID_TRIGGER_TYPES,
    CrawledPageListResponse,
    CrawledPageResponse,
    CrawlHistoryListResponse,
    CrawlHistoryResponse,
    CrawlProgressResponse,
    CrawlStartRequest,
    CrawlStopResponse,
)
from app.schemas.crawled_page import (
    CrawledPageCreate,
    CrawlStatusResponse,
    PageLabelsUpdate,
    PageSummary,
    ProgressCounts,
    TaxonomyLabel,
    TaxonomyResponse,
    UrlsUploadRequest,
    UrlUploadResponse,
)
from app.schemas.crawled_page import (
    CrawledPageResponse as CrawledPageFullResponse,
)
from app.schemas.internal_link import (
    AddLinkRequest,
    AnchorSuggestionsResponse,
    EditLinkRequest,
    InternalLinkResponse,
    LinkMapPageSummary,
    LinkMapResponse,
    LinkPlanRequest,
    LinkPlanStatusResponse,
    PageLinksResponse,
)
from app.schemas.keyword_research import (
    KeywordIdeaRequest,
    KeywordIdeaResponse,
    KeywordResearchFullRequest,
    KeywordResearchFullResponse,
    KeywordResearchStatsResponse,
    KeywordSpecificityRequest,
    KeywordSpecificityResponse,
    KeywordVolumeDataResponse,
    KeywordVolumeRequest,
    KeywordVolumeResponse,
    KeywordWithVolume,
    PrimaryKeywordRequest,
    PrimaryKeywordResponse,
    SecondaryKeywordRequest,
    SecondaryKeywordResponse,
    VolumeStatsResponse,
)
from app.schemas.label import (
    BatchCollectionRequest,
    LabelAllRequest,
    LabelAllResponse,
    LabelBatchItemResponse,
    LabelBatchRequest,
    LabelBatchResponse,
    LabeledPageResponse,
    LabelGenerateRequest,
    LabelGenerateResponse,
    LabelPageIdsRequest,
    LabelPageIdsResponse,
    LabelStatsResponse,
)
from app.schemas.project import (
    VALID_PHASE_STATUSES,
    VALID_PHASES,
    VALID_PROJECT_STATUSES,
    PhaseStatusEntry,
    PhaseStatusUpdate,
    ProjectCreate,
    ProjectListResponse,
    ProjectResponse,
    ProjectUpdate,
)
from app.schemas.project_file import (
    ProjectFileList,
    ProjectFileResponse,
)
from app.schemas.reddit import (
    BulkCommentActionRequest,
    CommentApproveRequest,
    CommentRejectRequest,
    CrowdReplyTaskResponse,
    RedditAccountCreate,
    RedditAccountResponse,
    RedditAccountUpdate,
    RedditCommentResponse,
    RedditPostResponse,
    RedditProjectConfigCreate,
    RedditProjectConfigResponse,
)

__all__ = [
    # Content Brief schemas
    "ContentBriefRequest",
    "ContentBriefBatchRequest",
    "ContentBriefResponse",
    "ContentBriefCreateResponse",
    "ContentBriefBatchItemResponse",
    "ContentBriefBatchResponse",
    "ContentBriefStatsResponse",
    "HeadingTargetSchema",
    "KeywordTargetSchema",
    "LSITermSchema",
    "EntitySchema",
    "RelatedQuestionSchema",
    "RelatedSearchSchema",
    "CompetitorSchema",
    # Content Score schemas
    "ContentScoreRequest",
    "ContentScoreBatchRequest",
    "ContentScoreResponse",
    "ContentScoreCreateResponse",
    "ContentScoreBatchItemResponse",
    "ContentScoreBatchResponse",
    "ContentScoreStatsResponse",
    "KeywordAnalysisSchema",
    "KeywordSectionAnalysisSchema",
    "LSICoverageSchema",
    "LSICoverageItemSchema",
    "HeadingAnalysisSchema",
    "HeadingLevelAnalysisSchema",
    "RecommendationSchema",
    # Project schemas
    "VALID_PROJECT_STATUSES",
    "VALID_PHASE_STATUSES",
    "VALID_PHASES",
    "PhaseStatusEntry",
    "ProjectCreate",
    "ProjectUpdate",
    "PhaseStatusUpdate",
    "ProjectResponse",
    "ProjectListResponse",
    # Crawl schemas
    "VALID_CRAWL_STATUSES",
    "VALID_TRIGGER_TYPES",
    "CrawlStartRequest",
    "CrawlHistoryResponse",
    "CrawlHistoryListResponse",
    "CrawledPageResponse",
    "CrawledPageListResponse",
    "CrawlProgressResponse",
    "CrawlStopResponse",
    # Cluster schemas
    "ClusterCreate",
    "ClusterPageResponse",
    "ClusterResponse",
    "ClusterListResponse",
    "ClusterPageUpdate",
    # Categorize schemas
    "CategorizeRequest",
    "BatchPageRequest",
    "CategorizePageIdsRequest",
    "CategorizeAllRequest",
    "CategorizeBatchRequest",
    "ContentSignalResponse",
    "ContentAnalysisResponse",
    "CategorizeResponse",
    "CategorizedPageResponse",
    "CategorizePageIdsResponse",
    "CategorizeAllResponse",
    "CategorizeStatsResponse",
    "UpdateCategoryRequest",
    "UpdateCategoryResponse",
    # Label schemas
    "LabelGenerateRequest",
    "BatchCollectionRequest",
    "LabelBatchRequest",
    "LabelPageIdsRequest",
    "LabelAllRequest",
    "LabelGenerateResponse",
    "LabelBatchItemResponse",
    "LabelBatchResponse",
    "LabeledPageResponse",
    "LabelPageIdsResponse",
    "LabelAllResponse",
    "LabelStatsResponse",
    # Keyword Research schemas
    "KeywordIdeaRequest",
    "KeywordIdeaResponse",
    "KeywordVolumeRequest",
    "KeywordVolumeResponse",
    "KeywordVolumeDataResponse",
    "VolumeStatsResponse",
    "KeywordWithVolume",
    "KeywordSpecificityRequest",
    "KeywordSpecificityResponse",
    "PrimaryKeywordRequest",
    "PrimaryKeywordResponse",
    "SecondaryKeywordRequest",
    "SecondaryKeywordResponse",
    "KeywordResearchFullRequest",
    "KeywordResearchFullResponse",
    "KeywordResearchStatsResponse",
    # Project File schemas
    "ProjectFileResponse",
    "ProjectFileList",
    # Brand Config schemas
    "BrandConfigResponse",
    "RegenerateRequest",
    "SectionUpdate",
    "VALID_SECTION_NAMES",
    # Brand Config Generation schemas
    "GenerationStatusResponse",
    # Content Generation schemas
    "ContentGenerationTriggerResponse",
    "ContentGenerationStatus",
    "PageGenerationStatusItem",
    "BriefSummary",
    "PageContentResponse",
    "PromptLogResponse",
    # Internal Link schemas
    "LinkPlanRequest",
    "LinkPlanStatusResponse",
    "InternalLinkResponse",
    "PageLinksResponse",
    "LinkMapPageSummary",
    "LinkMapResponse",
    "AddLinkRequest",
    "EditLinkRequest",
    "AnchorSuggestionsResponse",
    # Blog schemas
    "BlogCampaignCreate",
    "BlogPostResponse",
    "BlogCampaignResponse",
    "BlogCampaignListItem",
    "BlogPostUpdate",
    "BlogContentUpdateRequest",
    "BlogPostGenerationStatusItem",
    "BlogContentGenerationStatus",
    "BlogContentTriggerResponse",
    "BlogBulkApproveResponse",
    "BlogExportItem",
    "BlogLinkPlanTriggerResponse",
    "BlogLinkStatusResponse",
    "BlogLinkMapItem",
    "BlogLinkMapResponse",
    # Reddit schemas
    "RedditAccountCreate",
    "RedditAccountUpdate",
    "RedditAccountResponse",
    "RedditProjectConfigCreate",
    "RedditProjectConfigResponse",
    "RedditPostResponse",
    "RedditCommentResponse",
    "CommentApproveRequest",
    "CommentRejectRequest",
    "BulkCommentActionRequest",
    "CrowdReplyTaskResponse",
    # CrawledPage schemas
    "CrawledPageCreate",
    "CrawledPageFullResponse",
    "CrawlStatusResponse",
    "PageSummary",
    "ProgressCounts",
    "TaxonomyLabel",
    "TaxonomyResponse",
    "UrlsUploadRequest",
    "UrlUploadResponse",
    "PageLabelsUpdate",
]
